### ISSUE TITLE
Navigation right sidebar "Back to top" looks like a regular link

### ISSUE THREAD

**Issue by barrymcgee** [ubuntudesign/vanilla-docs-theme#15]
_From @pmatulis on December 5, 2016 16:52_

The navigation right sidebar has a "Back to top" link that appears when the page is scrolled down. It ends up looking like a regular link. Can this be improved? For example, a new section can be added just for that one link:

```
VERSIONS

2.0  2.1

----------------

CONTENTS

link
link
link

----------------

Back to top
```

_Copied from original issue: ubuntudesign/docs-vanilla-theme#49_

**Comment by barrymcgee** [comment]
_From @spencerbygraves on December 6, 2016 11:23_

Thanks @pmatulis We're currently updating the docs theme design, this is one of the areas we're looking at.

**Comment by yaili** [comment]
I'm closing this as it's covered by #1
