### ISSUE TITLE
Navigation right sidebar is not distinguishable from the main page

### ISSUE THREAD

**Issue by barrymcgee** [ubuntudesign/vanilla-docs-theme#16]
_From @pmatulis on December 5, 2016 16:46_

The navigation right sidebar could use some highlighting to distinguish it from a page's main body.

_Copied from original issue: ubuntudesign/docs-vanilla-theme#48_

**Comment by yaili** [comment]
Hi @pmatulis

Could you expand a little bit on what you mean by highlighting. @spencerbygraves has created a new design for the ToC area on #1 - do you mean even more distinction?

**Comment by nottrobin** [comment]
@pmatulis I'm closing this, as I hope it will be addressed in #1. Please re-open (with a little more details) if you still feel it's a problem.
