### ISSUE TITLE
table of contents: Should "back to top" be more distinct?

### ISSUE THREAD

**Issue by barrymcgee** [ubuntudesign/vanilla-docs-theme#2]
_From @nottrobin on December 8, 2016 17:17_

I think we should make the "back to top" link stand out a bit more. Different colour? Different size? Icon?

_Copied from original issue: ubuntudesign/docs-vanilla-theme#57_

**Comment by barrymcgee** [comment]
_From @spencerbygraves on December 8, 2016 17:19_

I think we want to separate this link from the others, probably with a grey horizontal line.

Could you also look at this please? I think it makes sense - #51 

Thanks

**Comment by yaili** [comment]
Similar to #15?

**Comment by spencerbygraves** [comment]
The design in #1 covers this, plus a few other issues.
