### ISSUE TITLE
TOC on right needs separate headings 

### ISSUE THREAD

**Issue by barrymcgee** [ubuntudesign/vanilla-docs-theme#3]
_From @knitzsche on December 8, 2016 16:32_

Look at this page: http://docs.ubuntu.com/core/en/guides/intro/security

One cannot tell how many headings are in the generated TOC on the right.

Maybe bullet points or lightly more vertical white space between headings?

_Copied from original issue: ubuntudesign/docs-vanilla-theme#56_

**Comment by yaili** [comment]
This is addressed in @spencerbygraves 's design for issue #1 and I think @nottrobin might have even already done some code changes for this, but not sure.

**Comment by nottrobin** [comment]
While I agree this is an important issue, I haven't done any work on this yet, and I doubt I'll have space to for a few weeks. If anyone else have time to pick this up that would be great.

**Comment by nottrobin** [comment]
Closing this as I believe it's addressed in #1. Re-open if you disagree.
