### ISSUE TITLE
table of contents: Should we reconsider the defaults?

### ISSUE THREAD

**Issue by barrymcgee** [ubuntudesign/vanilla-docs-theme#4]
_From @nottrobin on December 8, 2016 16:32_

Currently, it's off by default, and can be enabled with:

``` markdown
---
table_of_contents: true
---
```

I believe more pages *don't* need it than *do* because most pages are quite short. However, instead of manually turning it on, should we make it turn on when there are more than a certain number (e.g. `>= 4`) of headings to list?

I'd prefer enforcing a convention over configuration, unless there's a good argument for configuring it specifically.

_Copied from original issue: ubuntudesign/docs-vanilla-theme#55_

**Comment by barrymcgee** [comment]
_From @pmatulis on December 16, 2016 14:46_

The thing is that sometimes you have just 2 sub-headings but with a lot of text in between (makes sense to have a TOC in this case) and sometimes you have several sub-headings with very little text in between. Why do you want to default to enabled (or auto-enabled) and not let the writer decide?

**Comment by yaili** [comment]
Should we leave it on by default and the author can turn it off then? Making it clear that that option is there if they see it straight away.

**Comment by nottrobin** [comment]
It would be very easy to programme a rule here. We can simply make it so that when there are more than x headings, the TOC is displayed. Shall we say, when there are 3 or more sub-headings? Then we don't need an option. @pmatulis @yaili does that seem to make sense?

**Comment by nottrobin** [comment]
I'm closing this issue as this will actually be implemented in documentation builder - I filed an issue over there: https://github.com/CanonicalLtd/documentation-builder/issues/50
