### ISSUE TITLE
table of contents: Position marker

### ISSUE THREAD

**Issue by barrymcgee** [ubuntudesign/vanilla-docs-theme#5]
_From @nottrobin on December 8, 2016 16:29_

Could we indicate somehow which point in the TOC list you're currently scrolled to? E.g. with chevrons (">>")?

_Copied from original issue: ubuntudesign/docs-vanilla-theme#54_

**Comment by yaili** [comment]
Would you mind looking at this @spencerbygraves if you have some time :)

**Comment by spencerbygraves** [comment]
It's included in the design shown in #1
